<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
    <line>
      <![CDATA[<a href=file:///C:\Users\560320\Desktop\WinfieldUnited\JDEWinfield/ScreenShotLib/Errors found>click here to open screenshot</a>]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="77127" started-at="2019-06-18T15:40:55Z" finished-at="2019-06-18T15:42:12Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="77127" started-at="2019-06-18T15:40:55Z" finished-at="2019-06-18T15:42:12Z">
      <class name="com.lol.tests.CSvc04_SalesOrder_Accounting">
        <test-method status="PASS" signature="start()[pri:0, instance:com.lol.tests.CSvc04_SalesOrder_Accounting@1ed4004b]" name="start" is-config="true" duration-ms="11" started-at="2019-06-18T10:40:55Z" finished-at="2019-06-18T10:40:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- start -->
        <test-method status="PASS" signature="launch()[pri:0, instance:com.lol.tests.CSvc04_SalesOrder_Accounting@1ed4004b]" name="launch" is-config="true" duration-ms="446" started-at="2019-06-18T10:40:55Z" finished-at="2019-06-18T10:40:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launch -->
        <test-method status="PASS" signature="startTest(java.lang.reflect.Method)[pri:0, instance:com.lol.tests.CSvc04_SalesOrder_Accounting@1ed4004b]" name="startTest" is-config="true" duration-ms="13603" started-at="2019-06-18T10:40:55Z" finished-at="2019-06-18T10:41:09Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.lol.tests.CSvc04_SalesOrder_Accounting.CSV04() throws java.io.IOException,java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method status="FAIL" signature="CSV04()[pri:0, instance:com.lol.tests.CSvc04_SalesOrder_Accounting@1ed4004b]" name="CSV04" duration-ms="63062" started-at="2019-06-18T10:41:09Z" finished-at="2019-06-18T10:42:12Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.lol.tests.CSvc04_SalesOrder_Accounting.CSV04(CSvc04_SalesOrder_Accounting.java:172)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[<a href=file:///C:\Users\560320\Desktop\WinfieldUnited\JDEWinfield/ScreenShotLib/Errors found>click here to open screenshot</a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- CSV04 -->
        <test-method status="PASS" signature="teartown()[pri:0, instance:com.lol.tests.CSvc04_SalesOrder_Accounting@1ed4004b]" name="teartown" is-config="true" duration-ms="2767" started-at="2019-06-18T10:42:12Z" finished-at="2019-06-18T10:42:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teartown -->
      </class> <!-- com.lol.tests.CSvc04_SalesOrder_Accounting -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
